<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.17">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PDKS.Data\PDKS.Data.csproj" />
    <ProjectReference Include="..\PDKS.Entities\PDKS.Entities.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\Personnel\Data\" />
    <Folder Include="Areas\Personnel\Models\" />
  </ItemGroup>

</Project>
